
package com.chenghui.agriculture.ws.client.website;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-19T12:18:30.313+08:00
 * Generated source version: 3.1.2
 * 
 */
public final class UserPersonalOperation_UserPersonalOperationImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impls.ws.credit.chenghui.com/", "websiteOper");

    private UserPersonalOperation_UserPersonalOperationImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WebsiteOper.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WebsiteOper ss = new WebsiteOper(wsdlURL, SERVICE_NAME);
        UserPersonalOperation port = ss.getUserPersonalOperationImplPort();  
        
        {
        System.out.println("Invoking login...");
        java.lang.String _login_idNumber = "";
        java.lang.String _login_password = "";
        java.lang.String _login__return = port.login(_login_idNumber, _login_password);
        System.out.println("login.result=" + _login__return);


        }
        {
        System.out.println("Invoking queryCreditRecords...");
        java.lang.Long _queryCreditRecords_personalId = null;
        javax.xml.datatype.XMLGregorianCalendar _queryCreditRecords_startTime = null;
        javax.xml.datatype.XMLGregorianCalendar _queryCreditRecords_endTime = null;
        java.lang.String _queryCreditRecords__return = port.queryCreditRecords(_queryCreditRecords_personalId, _queryCreditRecords_startTime, _queryCreditRecords_endTime);
        System.out.println("queryCreditRecords.result=" + _queryCreditRecords__return);


        }
        {
        System.out.println("Invoking queryCreditRating...");
        java.lang.Long _queryCreditRating_personalId = null;
        java.lang.String _queryCreditRating__return = port.queryCreditRating(_queryCreditRating_personalId);
        System.out.println("queryCreditRating.result=" + _queryCreditRating__return);


        }

        System.exit(0);
    }

}
