package com.chenghui.agriculture.ws.client.website;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-19T12:18:30.344+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://interfaces.ws.credit.chenghui.com/", name = "UserPersonalOperation")
@XmlSeeAlso({ObjectFactory.class})
public interface UserPersonalOperation {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://interfaces.ws.credit.chenghui.com/", className = "com.chenghui.agriculture.ws.client.website.Login")
    @WebMethod
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://interfaces.ws.credit.chenghui.com/", className = "com.chenghui.agriculture.ws.client.website.LoginResponse")
    public java.lang.String login(
        @WebParam(name = "idNumber", targetNamespace = "")
        java.lang.String idNumber,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryCreditRecords", targetNamespace = "http://interfaces.ws.credit.chenghui.com/", className = "com.chenghui.agriculture.ws.client.website.QueryCreditRecords")
    @WebMethod
    @ResponseWrapper(localName = "queryCreditRecordsResponse", targetNamespace = "http://interfaces.ws.credit.chenghui.com/", className = "com.chenghui.agriculture.ws.client.website.QueryCreditRecordsResponse")
    public java.lang.String queryCreditRecords(
        @WebParam(name = "personalId", targetNamespace = "")
        java.lang.Long personalId,
        @WebParam(name = "startTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar startTime,
        @WebParam(name = "endTime", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endTime
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryCreditRating", targetNamespace = "http://interfaces.ws.credit.chenghui.com/", className = "com.chenghui.agriculture.ws.client.website.QueryCreditRating")
    @WebMethod
    @ResponseWrapper(localName = "queryCreditRatingResponse", targetNamespace = "http://interfaces.ws.credit.chenghui.com/", className = "com.chenghui.agriculture.ws.client.website.QueryCreditRatingResponse")
    public java.lang.String queryCreditRating(
        @WebParam(name = "personalId", targetNamespace = "")
        java.lang.Long personalId
    );
}
