package com.chenghui.agriculture.ws.client.website;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-19T12:18:30.360+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "websiteOper", 
                  wsdlLocation = "http://192.168.0.222:8080/credit_reference_center/service/websiteOper?wsdl",
                  targetNamespace = "http://impls.ws.credit.chenghui.com/") 
public class WebsiteOper extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impls.ws.credit.chenghui.com/", "websiteOper");
    public final static QName UserPersonalOperationImplPort = new QName("http://impls.ws.credit.chenghui.com/", "UserPersonalOperationImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.222:8080/credit_reference_center/service/websiteOper?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebsiteOper.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.222:8080/credit_reference_center/service/websiteOper?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebsiteOper(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebsiteOper(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebsiteOper() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns UserPersonalOperation
     */
    @WebEndpoint(name = "UserPersonalOperationImplPort")
    public UserPersonalOperation getUserPersonalOperationImplPort() {
        return super.getPort(UserPersonalOperationImplPort, UserPersonalOperation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserPersonalOperation
     */
    @WebEndpoint(name = "UserPersonalOperationImplPort")
    public UserPersonalOperation getUserPersonalOperationImplPort(WebServiceFeature... features) {
        return super.getPort(UserPersonalOperationImplPort, UserPersonalOperation.class, features);
    }

}
