package com.chenghui.agriculture.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-19T12:27:38.169+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "helloWorld", 
                  wsdlLocation = "http://192.168.0.222:8080/credit_reference_center/service/helloWorld?wsdl",
                  targetNamespace = "http://impls.ws.credit.chenghui.com/") 
public class HelloWorld_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impls.ws.credit.chenghui.com/", "helloWorld");
    public final static QName HelloWorldImplPort = new QName("http://impls.ws.credit.chenghui.com/", "HelloWorldImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.222:8080/credit_reference_center/service/helloWorld?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWorld_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.222:8080/credit_reference_center/service/helloWorld?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWorld_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorld_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorld_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    




    /**
     *
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldImplPort")
    public HelloWorld getHelloWorldImplPort() {
        return super.getPort(HelloWorldImplPort, HelloWorld.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorld
     */
    @WebEndpoint(name = "HelloWorldImplPort")
    public HelloWorld getHelloWorldImplPort(WebServiceFeature... features) {
        return super.getPort(HelloWorldImplPort, HelloWorld.class, features);
    }

}
